import { Injectable } from '@angular/core';
import { Cristales } from 'src/app/models/cristales';
import { Libros } from 'src/app/models/libros';
import { Elementos } from 'src/app/models/elementos';

@Injectable({
  providedIn: 'root'
})
export class TiendaService {
  constructor() { }
  //! inicialización de mis interfaces
  cristal: Cristales = {
    uid: '',
    nombre: '',
    beneficios: '',
    limpieza: '',
    precio: 0,
    destacado: false,
    imagenUrl: '',
    favorito: false,
  }

  elemento: Elementos = {
    uid: '',
    nombre: '',
    cantidadPorPaquete: 0,
    sabor: '',
    precio: 0,
    destacado: false,
    imagenUrl: '',
    favorito: false,
  }

  libro: Libros = {
    uid: '',
    titulo: '',
    descripcion: '',
    autor: '',
    precio: 0,
    destacado: false,
    imagenUrl: '',
    favorito: false,
  }

  // ------------------------------------------------------------------------------------------
  cristalesProd: any[] = [
    {
      uid: '',
      nombre: 'Dije de ágata fucsia',
      beneficios: 'La ágata favorece la calma y la armonía. Potencia la concentración, fomenta el amor y la sanación interna. Además, esta piedra te ayuda a eliminar la negatividad y la ira del corazón. Te anima a seguir adelante y a promover el amor propio y la valentía.',
      limpieza: 'Recuerda purificar las piedras de ágata fucsia con agua. También puedes limpiarlas con salvia blanca o palo santo. Si prefieres, puedes cargarlas con la energía de la luz de la luna o del sol.',
      precio: 250,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Dije de amatista',
      beneficios: 'La amatista es especial para transmutar la energía en amor. Se considera que promueve la estabilidad emocional y es ideal para las sesiones de meditación. Te ayuda a tomar mejores decisiones y a conciliar el sueño si sufres de insomnio o pesadillas recurrentes.',
      limpieza: 'Para limpiar una amatista, usa tierra, agua y sal, incienso, con el sol, con la luna e incluso con otra piedra energética. La mejor para tí dependerá de qué herramientas tienes a tu disposición así que prueba la que mejor se te acomode.',
      precio: 250,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Dije de ámbar',
      beneficios: 'Se dice que ayuda en diferentes procesos de sanación, transmuta la energía negativa y promueve la energía positiva lo que también ayuda a acelerar los procesos de curación. También te llena de vitalidad y potencia tu equilibrio emocional.',
      limpieza: 'Para limpiar tu piedra ambarina, simplemente enciende una varita de incienso o sahumerio y pasa tu colgante de ámbar Detallesamente a través del humo pero no la mojes',
      precio: 350,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Dije de apatita azul',
      beneficios: 'La apatita azul propicia la motivación y ayuda a conservar la energía. Es apreciada por sus propiedades que combaten la negatividad y promueven la creatividad y la sabiduría. Se dice que ayuda a calmar la pena y la ira. En su color azul, la apatita estimula la comunicación y alivia las afecciones emocionales.',
      limpieza: 'Puedes limpiarla haciendo uso de la sal marina. Pero si lo deseas puedes enterrar la piedra en agua con suficiente arroz; pasarla bajo una corriente de agua natural o dejarla durante unos minutos en el grifo de tu casa para que al momento de fluir las energías negativas se despeguen de la piedra; también puedes limpiarla con humo de incienso o enterrarla en una maceta o el jardín por dos noches consecutivas.',
      precio: 350,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Dije de calcita azul',
      beneficios: 'La calcita azul es conocida por sus propiedades relajantes. Se dice que ayuda a eliminar las energías negativas y a evitar la ansiedad. Como los otros cristales de color azul, ayuda a mejorar tus procesos de comunicación.',
      limpieza: 'Puedes  colocarla en el medio de un círculo de cuarzos de cristal, a los cuales se les pedirá que absorban y limpien todas estas energías. Otra forma será sumergirla en agua de mar por un rato y secarla con cuidado.',
      precio: 300,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Dije de citrino',
      beneficios: 'El citrino es regenerador y limpiador. También promueve la generación de energía y estimula la creatividad. Es una piedra que atrae la abundancia y la prosperidad. Además, ayuda a mirar las diferentes situaciones con actitud positiva y optimista.',
      limpieza: 'Con agua salada, después sumergirla por aproximadamente unos 10 minutos para que las energías viejas vayan quemándose y así abriendo paso a unas nuevas. Pasado el tiempo límite, la sacas y le retiras toda el agua con una nueva agua templada. Coloca el citrino en una zona que toque la luz del sol y la luz de la luna, logrando después de 24 horas que esté completamente cargado.',
      precio: 200,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Dije de cuarzo blanco',
      beneficios: 'Al cuarzo cristal o blanco se le atribuyen propiedades como la protección, pues absorbe y bloquea las energías negativas. Ayuda a mejorar la actitud, favorece la paz y la tranquilidad. Es ideal para meditar y conservar la concentración. También es utilizado en procesos de sanación. Además, es un buen conductor de energía.',
      limpieza: 'Lavar con agua corriente y sal marina aproximadamente entre tres y cinco minutos la piedra, con el fin de limpiar todas las energías de la misma. O dejarla remojando durante el mismo tiempo en agua salada.Otra forma de purificar el cuarzo es utilizando sahumerios de mirra o ponerlo en contacto con un cristal de roca.',
      precio: 200,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Dije de fluorita',
      beneficios: 'La fluorita está relacionada con mantener la concentración y conciliar el sueño. Además, fomenta la paz interior y ayuda a la meditación. La fluorita también es útil para combatir la radiación de los diferentes dispositivos electrónicos.',
      limpieza: 'Debes sumergirla en un recipiente que contenga una infusión fría de salvia y agua destilada, durante 30 minutos. También puede ser únicamente agua limpia y pura. No la limpies con agua y sal porque perdería su brillo. Tampoco uses productos químicos o de limpieza.',
      precio: 350,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Dije de rubí verde',
      beneficios: 'Los rubíes han sido la piedra preciosa de los regentes dominantes y de la nobleza. Ofrece vitalidad y brío al portador, permitiendo que viva su vida al máximo y que aproveche cada oportunidad positiva en su camino.',
      limpieza: 'El rubí es una piedra preciosa durable por lo que puede resistir casi cualquier tipo de limpieza con agua, sol o humo, pero particularmente me gusta el tradicional método hindú de la India donde el rubí es especialmente venerado.',
      precio: 350,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Dije de turmalina negra',
      beneficios: 'La turmalina negra es una piedra protectora, excelente para repeler energías negativas. Aporta neutralidad en momentos de desesperación. Además, portar una piedra de turmalina es muy beneficioso para evitar daños que te puedes hacer a ti mismo.',
      limpieza: 'Colócala durante toda una noche a la luz de la luna, de ser posible con agua marina. Otro método es colocarla en un envase de vidrio con agua y sal marina. Transcurrida la noche, se debe lavar con agua natural la piedra y dejar secar  en un lugar soleado.',
      precio: 200,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    }
  ]
  //! ------------------------------------------------------
  librosProd: any[] = [
    {
      uid: '',
      titulo: 'Terapia de runas',
      descripcion: 'Una guía para aprender sobre el poder de la magia nórdica y su oráculo',
      autor: 'Eleonora Merighi',
      precio: 12600,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      titulo: '60 Tiradas fáciles de tarot',
      descripcion: 'Una guía sensilla, práctica y divertida con 60 tiradas a tu alcance',
      autor: 'Ramón Plana y Olga Roig',
      precio: 13300,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      titulo: 'El gran libro del tarot',
      descripcion: 'Una obra excepcional, distinta a todo lo publicado',
      autor: 'Emilio Salas',
      precio: 14100,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      titulo: 'El tarot como llave',
      descripcion: 'Una invitación a conocer el Tarot y a dejarse seducir por su magia.',
      autor: 'Dalia Walker',
      precio: 9100,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      titulo: 'Reiki: mensajes del universo',
      descripcion: 'Incluye libros y cartas',
      autor: 'Jhonny De Carli',
      precio: 13900,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      titulo: 'El oraculo de la transformación',
      descripcion: '44 cartas y guía explicativa',
      autor: 'Doreen Virtue',
      precio: 10900,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      titulo: 'El manual del tarot egipcio',
      descripcion: 'La cábala de predicción',
      autor: 'Iglesias Janeiro',
      precio: 13700,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      titulo: 'El oráculo astrológico',
      descripcion: 'Contiene libros y cartas',
      autor: 'Ana Lia Ríos',
      precio: 10650,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      titulo: 'El tarot del amor',
      descripcion: 'Incluye cartas',
      autor: 'Laura Podio',
      precio: 11500,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      titulo: 'La sanación con símbolos',
      descripcion: '64 símbolos',
      autor: 'Petra Neumayer',
      precio: 10200,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
  ]
  //! ------------------------------------------------------
  elementosProd: any[] = [
    {
      uid: '',
      nombre: 'Sahumerios magistrales Aromanza: relajación',
      cantidadPorPaquete: 8,
      sabor: 'Mirra consagrada',
      precio: 1100,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Sahumerios magistrales Aromanza: gratitud',
      cantidadPorPaquete: 8,
      sabor: 'Jazmín de la vida',
      precio: 1100,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Sahumerios magistrales Aromanza: armonía',
      cantidadPorPaquete: 8,
      sabor: 'Incienso consagrado',
      precio: 1100,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Sahumerios tibetanos Aromanza: inspiración',
      cantidadPorPaquete: 8,
      sabor: 'Cristobal colón',
      precio: 1200,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Sahumerios tibetanos Aromanza: equilibrio',
      cantidadPorPaquete: 8,
      sabor: 'Ébano marfil',
      precio: 1200,
      destacado: true,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Sahumerios tibetanos Aromanza: abundancia',
      cantidadPorPaquete: 8,
      sabor: 'Vainillas encantadas',
      precio: 1200,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Inciensos Sagrada Madre con romero',
      cantidadPorPaquete: 1,
      sabor: 'Romero',
      precio: 980,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Inciensos Sagrada Madre con yagra',
      cantidadPorPaquete: 1,
      sabor: 'Yagra',
      precio: 0,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Inciensos Sagrada Madre con champa',
      cantidadPorPaquete: 1,
      sabor: 'Champa',
      precio: 980,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
    {
      uid: '',
      nombre: 'Pack de 25 sahumerios triple empaste',
      cantidadPorPaquete: 12,
      sabor: 'Surtidos sabores',
      precio: 980,
      destacado: false,
      imagenUrl: '',
      favorito: false,
    },
  ]
}
